{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "empty-bucket-controller.fullname" . }}
  labels:
    {{- include "empty-bucket-controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "empty-bucket-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "empty-bucket-controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
