{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "empty-bucket-controller.fullname" . }}
labels:
    {{- include "empty-bucket-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: ["s3.services.k8s.aws"]
    resources: ["buckets"]
    verbs: ["get", "list", "watch"]
{{- end }}
