replicaCount: 1
image:
  repository: ghcr.io/agologan/ack-s3-empty-bucket-controller
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: {}

serviceAccount:
  create: true
  annotations: {}

clusterRole:
  create: true

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

resources: {}

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 5
  # targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
